export const GET_ISSUES_REQUEST = 'GET_ISSUES_REQUEST';
export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_FAIL = 'GET_ISSUES_FAIL';

export const SAVE_ISSUES = 'SAVE_ISSUES';
export const SAVE_EDITED_ID = 'SAVE_EDITED_ID';
export const EDIT_ISSUE_REQUEST = 'EDIT_ISSUE_REQUEST';
export const EDIT_ISSUE_SUCCESS = 'EDIT_ISSUE_SUCCESS';
export const EDIT_ISSUE_FAIL = 'EDIT_ISSUE_FAIL';
export const UPDATE_ISSUE = 'UPDATE_ISSUE';
export const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
export const CREATE_ISSUE_FAIL = 'CREATE_ISSUE_FAIL';
